name: flutter_app_badge
description: Plugin to update the app badge on the launcher iOS and macOS
version: 2.0.2
homepage: https://github.com/nazarpunk/flutter_app_badge

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterAppBadgePlugin

environment:
  sdk: ^3.0.6
  flutter: ">=3.10.6"