name: flutter_app_badge
description: Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
version: 2.0.0
homepage: https://github.com/nazarpunk/flutter_app_badge

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: nazarpunk.flutterappbadge
        pluginClass: FlutterAppBadgePlugin
      ios:
        pluginClass: FlutterAppBadgePlugin
      macos:
        pluginClass: FlutterAppBadgePlugin

environment:
  sdk: '>=3.0.6 <4.0.0'
